version: '3'
services:
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud_cliente
    volumes:
      - crud_cliente_project_avaliacao:/var/lib/mysql
    networks:
      - crud-cliente-spring

#  backend:
#    build: .
#    image: tiagocaguiar/crud-cliente-backend
#    ports:
#      - 8081:8080
#    volumes:
#      - ./:/app
#    depends_on:
#      - mysqldb
#    networks:
#      - crud-cliente-spring

volumes:
  crud_cliente_project_avaliacao:

networks:
  crud-cliente-spring:
