server:
  port: 8080

spring:
  application:
    name: crud_cliente
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/crud_cliente?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password